# Generated by Django 2.1 on 2019-01-28 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='item', max_length=250)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('description', models.CharField(default='description', max_length=250)),
                ('image', models.CharField(default='image', max_length=250)),
                ('product_ID', models.CharField(default='0000', max_length=4)),
                ('vat', models.FloatField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.Book')),
                ('shoe_size', models.CharField(default='00', max_length=2)),
            ],
            bases=('books.book',),
        ),
    ]
