# Generated by Django 2.1 on 2018-11-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='description', max_length=250),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(default='image', max_length=250),
        ),
        migrations.AddField(
            model_name='book',
            name='item',
            field=models.CharField(default='item', max_length=250),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.CharField(default='price', max_length=250),
        ),
    ]
