# Generated by Django 2.1 on 2018-11-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20181129_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ID',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
