# Generated by Django 2.1 on 2018-12-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ID',
            new_name='product_ID',
        ),
    ]
